[tool.poetry]
name = "pentestpal"
version = "0.1.0"
description = ""
authors = ["Mark Lechner <lechner.mark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
chromadb = "^0.4.20"
langchain = "^0.0.350"
beautifulsoup4 = "^4.12.2"
gpt4all = "^2.0.2"
langchainhub = "^0.1.14"
pypdf = "^3.17.2"
chainlit = "^0.7.700"
jupyter = "^1.0.0"
ipykernel = "^6.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
